import type {
  KineticCells,
  KineticEffects,
  KineticFlow,
  KineticMotion,
} from "./index.js";

export type KineticPreset = Readonly<{
  cells: KineticCells;
  effects: KineticEffects;
  flow: KineticFlow;
  motion: KineticMotion;
}>;

export const kineticPresets = Object.freeze({
  structural: Object.freeze({
    cells: Object.freeze({
      colorMode: "gradient",
      colors: Object.freeze(["#155e75", "#22d3ee", "#ecfeff"]),
      gap: 1,
      shape: "square",
      size: Object.freeze([40, 32, 24] as const),
    }),
    effects: Object.freeze({
      content: true,
      drift: true,
      tilt: true,
      wave: true,
    }),
    flow: Object.freeze({
      growth: 0.82,
      intensity: 1,
      maxCells: 420,
      overflow: 14,
      recovery: 1,
      speed: 1,
      thickness: 1,
      turbulence: 0.38,
      turbulenceScale: 4,
    }),
    motion: Object.freeze({
      contentLift: 12,
      contentTravel: 3,
      drift: 1.5,
      maxTilt: 1.35,
      response: 0.18,
      waveDuration: 640,
    }),
  }),
  locator: Object.freeze({
    cells: Object.freeze({
      colorMode: "single",
      colors: Object.freeze(["#67e8f9"]),
      gap: 0,
      shape: "hexagon",
      size: Object.freeze([40, 32, 26] as const),
    }),
    effects: Object.freeze({
      content: true,
      drift: false,
      tilt: true,
      wave: true,
    }),
    flow: Object.freeze({
      growth: 1,
      intensity: 1.35,
      maxCells: 420,
      overflow: 0,
      recovery: 1.15,
      speed: 1.15,
      thickness: 0.9,
      turbulence: 0.2,
      turbulenceScale: 4,
    }),
    motion: Object.freeze({
      contentLift: 10,
      contentTravel: 3,
      maxTilt: 1.35,
      response: 0.2,
      waveDuration: 560,
    }),
  }),
  laminar: Object.freeze({
    cells: Object.freeze({
      colorMode: "gradient",
      colors: Object.freeze(["#0e7490", "#67e8f9", "#ecfeff"]),
      gap: 1,
      shape: "circle",
      size: Object.freeze([42, 34, 26] as const),
    }),
    effects: Object.freeze({
      content: true,
      drift: false,
      tilt: true,
      wave: true,
    }),
    flow: Object.freeze({
      growth: 0.68,
      intensity: 0.9,
      maxCells: 420,
      overflow: 10,
      recovery: 1.25,
      speed: 1.2,
      thickness: 0.72,
      turbulence: 0.08,
      turbulenceScale: 6,
    }),
    motion: Object.freeze({
      contentLift: 8,
      contentTravel: 2,
      maxTilt: 1,
      response: 0.22,
      waveDuration: 620,
    }),
  }),
  material: Object.freeze({
    cells: Object.freeze({
      colorMode: "bands",
      colors: Object.freeze(["#22d3ee", "#a78bfa", "#f0abfc"]),
      gap: 1,
      shape: "hexagon",
      size: Object.freeze([40, 32, 24] as const),
    }),
    effects: Object.freeze({
      content: true,
      drift: true,
      tilt: true,
      wave: true,
    }),
    flow: Object.freeze({
      growth: 0.9,
      intensity: 1.12,
      maxCells: 480,
      overflow: 16,
      recovery: 1.08,
      speed: 0.95,
      thickness: 1.05,
      turbulence: 0.28,
      turbulenceScale: 4,
    }),
    motion: Object.freeze({
      contentLift: 12,
      contentTravel: 4,
      drift: 1.2,
      maxTilt: 1.35,
      response: 0.18,
      waveDuration: 680,
    }),
  }),
  tidal: Object.freeze({
    cells: Object.freeze({
      colorMode: "gradient",
      colors: Object.freeze(["#082f49", "#0284c7", "#67e8f9", "#f0fdfa"]),
      gap: 1,
      shape: "circle",
      size: Object.freeze([44, 34, 26] as const),
    }),
    effects: Object.freeze({
      content: true,
      drift: true,
      tilt: true,
      wave: true,
    }),
    flow: Object.freeze({
      growth: 0.8,
      intensity: 1.18,
      maxCells: 520,
      maxWaves: 4,
      multi: true,
      overflow: 22,
      recovery: 1.5,
      speed: 0.68,
      thickness: 1.42,
      turbulence: 0.52,
      turbulenceScale: 3,
    }),
    motion: Object.freeze({
      contentLift: 10,
      contentTravel: 3,
      drift: 1.8,
      maxTilt: 1.1,
      response: 0.14,
      waveDuration: 920,
    }),
  }),
  impact: Object.freeze({
    cells: Object.freeze({
      colorMode: "bands",
      colors: Object.freeze(["#fef08a", "#fb923c", "#f43f5e"]),
      gap: 0,
      shape: "diamond",
      size: Object.freeze([38, 30, 22] as const),
    }),
    effects: Object.freeze({
      content: true,
      drift: false,
      tilt: true,
      wave: true,
    }),
    flow: Object.freeze({
      growth: 1,
      intensity: 1.6,
      maxCells: 460,
      overflow: 24,
      recovery: 0.78,
      speed: 1.55,
      thickness: 1.62,
      turbulence: 0.42,
      turbulenceScale: 2.5,
    }),
    motion: Object.freeze({
      contentLift: 16,
      contentTravel: 4,
      maxTilt: 1.6,
      response: 0.3,
      waveDuration: 460,
    }),
  }),
} as const satisfies Readonly<Record<string, KineticPreset>>);
